### ISSUE TITLE
Broken Course Scheduler Bookstore Links

### ISSUE THREAD

**Issue by charlietharas** [WilliamsStudentsOnline/wso-react#272]
**Describe the bug**
Links to "View Course Book Information" in the course scheduler lead correctly to Follett bkstr URLs, but the URLs never contain any textbooks (even for classes that have textbook requirements).

**To Reproduce**
1. Go to course scheduler on the website
2. Find any given course that you *know* has a textbook requirement.
3. Click "View Course Book Information"

**Expected behavior**
Required books should be listed on the Follett page for corresponding courses.

**Platforms**
Consistent on all platforms since it is the Follett "API" that has changed (URL redirect will always go to a page that doesn't have courses)

**Additional context**
This might be something that Follett changed on their end, or they may no longer have information from Williams about required books for courses.

**Comment by yechs** [comment]
> This might be something that Follett changed on their end

yea most likely this. maybe they changed their URL format

**Comment by charlietharas** [comment]
Partially resolved with cfc8125 (fixes links for Winter Study and Spring 2024). The issue is in the `termID` flag in the HTTP request--changing this flag gets you into the course requirements for entirely different schools as well as semesters. I can't find our old flag for Fall 2023, but WS/S are working.

**This will likely break next fall**

**Comment by yechs** [comment]
I think it would be good if we can make it a config, so we don’t need to change it in code
