### ISSUE TITLE
Course scheduler default semester is always fall

### ISSUE THREAD

**Issue by charlietharas** [WilliamsStudentsOnline/wso-react#273]
**Describe the bug**
When opening the course scheduler catalog, "Fall" is always checked as default (and Winter and Spring unchecked) regardless of date, despite there being a function to supposedly handle this.

Expect to fix through debugging `getDefaultSemesterIndex()` in scheduler.js

**Comment by charlietharas** [comment]
Fixed by 153e104:
- Default semester selection behavior changed to not have winter study courses be the default during winter study (since it's too late for that)
- Fixed initial broken behavior (was due to faulty strings in constants.js)
- Automated constants.js so that the preregistration/semester dates do not *have* to be manually updated every year for the year (although the exact dates may still be off)

**Comment by yechs** [comment]
Related: #164
