### ISSUE TITLE
Ephmatch: no option to upload photo when creating profile

### ISSUE THREAD

**Issue by yechs** [WilliamsStudentsOnline/wso-react#295]
There are only options to change the photo once a profile has been created.

However, no options are available to change the photo while creating the profile (first-time user)

**Comment by Arsaluddin** [comment]
please assign this to me

**Comment by yechs** [comment]
> please assign this to me

@Arsaluddin Is this reply automated by filtering the label "good first issue"?

While we are open to outside contributions, our codebase assumes that the developers are Williams students and is hard to run otherwise. It is most likely that this issue will be fixed by one of our current active members.

**Comment by Arsaluddin** [comment]
@yechs no this is not automated ,

**Comment by yechs** [comment]
> @yechs no this is not automated ,

Oh wow... I'm surprised you found us. As I said, feel free to look around or contribute. However, it is most likely that you will need to be a Williams student to have access to certain features, let alone fix them. At this point, we only assign issues to our currently active developers.
